### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by davidstosik** [jbrooksuk/Sublime-Pebble#8]
Hello,

I'm trying to install Sublime-Pebble, and facing the following error.

```
reloading plugin Pebble.Pebble
reloading plugin Pebble.generate_completions
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 73, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 853, in _load_module
  File "<frozen importlib._bootstrap>", line 980, in get_code
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/home/sto/.config/sublime-text-3/Packages/Pebble/generate_completions.py", line 51
    except getopt.error, msg:
                       ^
SyntaxError: invalid syntax
```

I'm on Ubuntu 14.04, using Sublime build 3065. Am I doing something wrong, or is this a real syntax error?

Edit: looks like this syntax is not valid in Python 3.

**Comment by dstosik** [comment]
When I try to run any Pebble command from the Command Palette:

```
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 524, in run_
    return self.run(**args)
  File "exec in /opt/sublime_text/Packages/Default.sublime-package", line 168, in run
TypeError: sequence item 1: expected str instance, NoneType found
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 445, in is_enabled_
    raise ValueError("is_enabled must return a bool", self)
ValueError: ('is_enabled must return a bool', <Default.exec.ExecCommand object at 0x7fde88807cd0>)
```
